// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/printer_device.dart';
import 'models/printer_settings.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 5043545730990758507),
      name: 'PrinterDevice',
      lastPropertyId: const obx_int.IdUid(9, 182628850892559996),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6374545950572985942),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3762861479175685541),
            name: 'printerName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1243313015728898457),
            name: 'printerType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2424533090471855793),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 154371660968505114),
            name: 'isDefault',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 539833325422976193),
            name: 'isOnline',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4425968147713875553),
            name: 'lastDetected',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 3503819631298620264),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 182628850892559996),
            name: 'updatedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 7348221204909642677),
      name: 'PrinterSettings',
      lastPropertyId: const obx_int.IdUid(9, 8907243517727938760),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3155084742970970310),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5642145753721959110),
            name: 'key',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 3658789596920691935)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8747308591537297273),
            name: 'targetWidthMm',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8020136484404097469),
            name: 'targetHeightMm',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8044248964809771250),
            name: 'offsetXMm',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2535800298697913033),
            name: 'offsetYMm',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 1859202890250329246),
            name: 'scalePercent',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 9178454792200072193),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 8907243517727938760),
            name: 'updatedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 7348221204909642677),
      lastIndexId: const obx_int.IdUid(1, 3658789596920691935),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    PrinterDevice: obx_int.EntityDefinition<PrinterDevice>(
        model: _entities[0],
        toOneRelations: (PrinterDevice object) => [],
        toManyRelations: (PrinterDevice object) => {},
        getId: (PrinterDevice object) => object.id,
        setId: (PrinterDevice object, int id) {
          object.id = id;
        },
        objectToFB: (PrinterDevice object, fb.Builder fbb) {
          final printerNameOffset = fbb.writeString(object.printerName);
          final printerTypeOffset = object.printerType == null
              ? null
              : fbb.writeString(object.printerType!);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, printerNameOffset);
          fbb.addOffset(2, printerTypeOffset);
          fbb.addOffset(3, descriptionOffset);
          fbb.addBool(4, object.isDefault);
          fbb.addBool(5, object.isOnline);
          fbb.addInt64(6, object.lastDetected.millisecondsSinceEpoch);
          fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(8, object.updatedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final printerNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, '');
          final printerTypeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8);
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final isDefaultParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false);
          final isOnlineParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          final lastDetectedParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0));
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0));
          final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0));
          final object = PrinterDevice(
              printerName: printerNameParam,
              printerType: printerTypeParam,
              description: descriptionParam,
              isDefault: isDefaultParam,
              isOnline: isOnlineParam,
              lastDetected: lastDetectedParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    PrinterSettings: obx_int.EntityDefinition<PrinterSettings>(
        model: _entities[1],
        toOneRelations: (PrinterSettings object) => [],
        toManyRelations: (PrinterSettings object) => {},
        getId: (PrinterSettings object) => object.id,
        setId: (PrinterSettings object, int id) {
          object.id = id;
        },
        objectToFB: (PrinterSettings object, fb.Builder fbb) {
          final keyOffset = fbb.writeString(object.key);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, keyOffset);
          fbb.addFloat64(2, object.targetWidthMm);
          fbb.addFloat64(3, object.targetHeightMm);
          fbb.addFloat64(4, object.offsetXMm);
          fbb.addFloat64(5, object.offsetYMm);
          fbb.addFloat64(6, object.scalePercent);
          fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(8, object.updatedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final keyParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final targetWidthMmParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final targetHeightMmParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final offsetXMmParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final offsetYMmParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final scalePercentParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0));
          final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0));
          final object = PrinterSettings(
              key: keyParam,
              targetWidthMm: targetWidthMmParam,
              targetHeightMm: targetHeightMmParam,
              offsetXMm: offsetXMmParam,
              offsetYMm: offsetYMmParam,
              scalePercent: scalePercentParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [PrinterDevice] entity fields to define ObjectBox queries.
class PrinterDevice_ {
  /// See [PrinterDevice.id].
  static final id =
      obx.QueryIntegerProperty<PrinterDevice>(_entities[0].properties[0]);

  /// See [PrinterDevice.printerName].
  static final printerName =
      obx.QueryStringProperty<PrinterDevice>(_entities[0].properties[1]);

  /// See [PrinterDevice.printerType].
  static final printerType =
      obx.QueryStringProperty<PrinterDevice>(_entities[0].properties[2]);

  /// See [PrinterDevice.description].
  static final description =
      obx.QueryStringProperty<PrinterDevice>(_entities[0].properties[3]);

  /// See [PrinterDevice.isDefault].
  static final isDefault =
      obx.QueryBooleanProperty<PrinterDevice>(_entities[0].properties[4]);

  /// See [PrinterDevice.isOnline].
  static final isOnline =
      obx.QueryBooleanProperty<PrinterDevice>(_entities[0].properties[5]);

  /// See [PrinterDevice.lastDetected].
  static final lastDetected =
      obx.QueryDateProperty<PrinterDevice>(_entities[0].properties[6]);

  /// See [PrinterDevice.createdAt].
  static final createdAt =
      obx.QueryDateProperty<PrinterDevice>(_entities[0].properties[7]);

  /// See [PrinterDevice.updatedAt].
  static final updatedAt =
      obx.QueryDateProperty<PrinterDevice>(_entities[0].properties[8]);
}

/// [PrinterSettings] entity fields to define ObjectBox queries.
class PrinterSettings_ {
  /// See [PrinterSettings.id].
  static final id =
      obx.QueryIntegerProperty<PrinterSettings>(_entities[1].properties[0]);

  /// See [PrinterSettings.key].
  static final key =
      obx.QueryStringProperty<PrinterSettings>(_entities[1].properties[1]);

  /// See [PrinterSettings.targetWidthMm].
  static final targetWidthMm =
      obx.QueryDoubleProperty<PrinterSettings>(_entities[1].properties[2]);

  /// See [PrinterSettings.targetHeightMm].
  static final targetHeightMm =
      obx.QueryDoubleProperty<PrinterSettings>(_entities[1].properties[3]);

  /// See [PrinterSettings.offsetXMm].
  static final offsetXMm =
      obx.QueryDoubleProperty<PrinterSettings>(_entities[1].properties[4]);

  /// See [PrinterSettings.offsetYMm].
  static final offsetYMm =
      obx.QueryDoubleProperty<PrinterSettings>(_entities[1].properties[5]);

  /// See [PrinterSettings.scalePercent].
  static final scalePercent =
      obx.QueryDoubleProperty<PrinterSettings>(_entities[1].properties[6]);

  /// See [PrinterSettings.createdAt].
  static final createdAt =
      obx.QueryDateProperty<PrinterSettings>(_entities[1].properties[7]);

  /// See [PrinterSettings.updatedAt].
  static final updatedAt =
      obx.QueryDateProperty<PrinterSettings>(_entities[1].properties[8]);
}
